services:
  date:
    image: lizasmeh/result-date
    build:
      dockerfile: date.dockerfile
  result:
    image: lizasmeh/result
    build: .
    ports:
    - '3000:3000'
    env_file:
      - .env
    depends_on:
    - date